### ISSUE TITLE
Parser TYPES_OPERATORS does not have not_between

### ISSUE THREAD

**Issue by andrewSeldenrust** [fourlabsldn/QBJSParser#11]
Good Afternoon! 

I appreciate the work you guys have done to make QBJS usable for us Doctrine users!  

I ran into an error today - 
<img width="487" alt="screen shot 2017-08-18 at 2 52 56 pm" src="https://user-images.githubusercontent.com/25235489/29475393-20e36cac-8425-11e7-8314-a1b517fec4e4.png">

It looks like the TYPES_OPERATORS do not have the not_between operator for Date.

<img width="757" alt="screen shot 2017-08-18 at 2 49 53 pm" src="https://user-images.githubusercontent.com/25235489/29475401-317d235a-8425-11e7-96b4-b71cbbec53f9.png">

Here is a list of options QBJS allows a user to select. 

<img width="157" alt="screen shot 2017-08-18 at 2 56 56 pm" src="https://user-images.githubusercontent.com/25235489/29475482-8e868fd2-8425-11e7-9b83-aa4431dd2f89.png">

Any thoughts?  Is this something you guys can update? Thanks!

Andrew

**Comment by foaly-nr1** [comment]
Can you please test https://github.com/fourlabsldn/QBJSParser/pull/12 and let me know?

composer.json:
```json
"require" : {
    "fourlabs/qbjs-parser": "dev-not-between"
}
```

**Comment by bridgeenterprisesolutions** [comment]
@foaly-nr1 I am so sorry - I completely missed this. I appreciate you fixing this. Works like a charm.

**Comment by andrewSeldenrust** [comment]
@foaly-nr1 I am so sorry. I completely missed this. Thanks for your work! It functions like a charm
