### ISSUE TITLE
QueryBuilderJS 'NOT group' plugin not working

### ISSUE THREAD

**Issue by dlopeza** [fourlabsldn/QBJSParser#14]
I wish this feature could work:
https://querybuilder.js.org/plugins.html#not-group

In the js, not: true is passed but It´s not been parsed to the DQL

without NOT:

Query:
```
{"condition":"AND","rules":[{
"id":"empresa.siglas","field":"empresa.siglas","type":"string","input":"checkbox","operator":"equal","value":["XXX"]}],"not":false,"valid":true}
```
QueryString (from Debug):
`"SELECT object, object_empresa FROM AppBundle\Entity\Agente object  LEFT JOIN object.empresa object_empresa WHERE ( object_empresa.siglas = ?0 ) "
`
with NOT checked:
Query:
```
{"condition":"AND","rules":[{
"id":"empresa.siglas","field":"empresa.siglas","type":"string","input":"checkbox","operator":"equal","value":["XXX"]}],"not":true,"valid":true}
```
QueryString (from Debug):
`"SELECT object, object_empresa FROM AppBundle\Entity\Agente object  LEFT JOIN object.empresa object_empresa WHERE ( object_empresa.siglas = ?0 ) "
`

The DQL seems to be the same, despite the "not": truefrom the JS

**Comment by galeaspablo** [comment]
@dlopeza I have made a new release 1.1.0 with support for 'NOT group'. If you'd like to say thank you, the best way is to test it working. :)

**Comment by dlopeza** [comment]
I tested with QBJSParserBundle and I found that when I do:
```
{Not:false ->filter
     other group{
            Not: true -> filter
    }
}
```
I get an excepcion caused by an extra ')'

-
My QBJS Rules:
`{"condition":"AND","rules":[{"id":"sindicatos.siglas","field":"sindicatos.siglas","type":"string","input":"checkbox","operator":"equal","value":["SSP"]}],"not":true}],"not":false,"valid":true}`

Dql:

`SELECT object, object_dependencia, LEFT JOINS ....
	WHERE (
		 object_sindicatos.siglas = ?0 AND (
		 	 NOT (
		 	  object_dependencia.nombre = ?1 
		 	 ) 
		 ) 
	) )
`

**Comment by galeaspablo** [comment]
Great find! Thank you.

I've written a test against that edge case and made a new release (1.1.1). Please test again.

**Comment by dlopeza** [comment]
Now I can confirm it´s working!!!! Thank you !!!!!!
