### ISSUE TITLE
"WHERE NOT IN" Problems

### ISSUE THREAD

**Issue by dlopeza** [fourlabsldn/QBJSParser#19]
Let´s say I have an entity Person related (many to many) to an entity Languages.
I would filter Persons who don´t speak one ( or some) language(s).
The Query would be something like this:

`SELECT  P.*
FROM    person p
LEFT JOIN language l 
ON  p.value = l.value
WHERE   l.value IS NULL`

Is any way to do this?

**Comment by galeaspablo** [comment]
Yes, look at association entity in https://github.com/fourlabsldn/QBJSParser/blob/master/Documentation/Parsers/Doctrine.md for an example.
